param([switch]$Update, [string]$Godot = 'godot')
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
# Conservative code bundle, semantic scenes/resources are hashed by Godot itself.
$paths = [Collections.Generic.List[string]]::new()
foreach ($folder in @('gameplay', 'map_data', 'core/input', 'core/camera', 'visuals')) {
    Get-ChildItem (Join-Path $root $folder) -Recurse -File -Filter '*.gd' | ForEach-Object {
        if ($_.Name -ne 'map_code_manifest.gd') {
            $paths.Add($_.FullName.Substring($root.Length + 1).Replace('\', '/'))
        }
    }
}
$paths.Sort([StringComparer]::Ordinal)
$content = [Text.StringBuilder]::new()
foreach ($relative in $paths) {
    [void]$content.Append($relative + "`n")
    [void]$content.Append([IO.File]::ReadAllText((Join-Path $root $relative)).Replace("`r`n", "`n"))
}
$sha = [Security.Cryptography.SHA256]::Create()
$digest = [BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($content.ToString()))).Replace('-', '').ToLowerInvariant()
$sha.Dispose()
$manifest = "class_name MapCodeManifest`nextends RefCounted`n## Generated by check_trial_hash.ps1; identical code identity in exported builds.`nconst DIGEST: String = `"$digest`"`nconst PATHS: Array[String] = [`n"
foreach ($relative in $paths) { $manifest += "`t`"res://$relative`",`n" }
$manifest += "]`n"
$dataPaths = [Collections.Generic.List[string]]::new()
foreach ($folder in @('gameplay', 'core/input', 'core/camera', 'visuals')) {
    Get-ChildItem (Join-Path $root $folder) -Recurse -File | Where-Object { $_.Extension -in '.tscn', '.tres' } | ForEach-Object {
        $dataPaths.Add($_.FullName.Substring($root.Length + 1).Replace('\', '/'))
    }
}
$dataPaths.Sort([StringComparer]::Ordinal)
$manifest += "const DATA_PATHS: Array[String] = [`n"
foreach ($relative in $dataPaths) { $manifest += "`t`"res://$relative`",`n" }
$manifest += "]`n"
$path = Join-Path $root 'map_data/map_code_manifest.gd'
if ($Update) {
    [IO.File]::WriteAllText($path, $manifest, [Text.UTF8Encoding]::new($false))
} elseif ([IO.File]::ReadAllText($path).Replace("`r`n", "`n") -cne $manifest) {
    throw 'Gameplay code changed: run dev_tools/check_trial_hash.ps1 -Update after review'
}
# Start-Process must wait for the Windows engine, including its child console wrapper.
$logRoot = Join-Path $root 'builds/validation'
New-Item -ItemType Directory -Force $logRoot | Out-Null
$argsList = @('--headless', '--path', '.', '--script', 'dev_tools/bake_map_checksum.gd')
if ($Update) { $argsList += @('--', '--update') }
$process = Start-Process -FilePath $Godot -ArgumentList $argsList -WorkingDirectory $root -WindowStyle Hidden -PassThru -RedirectStandardOutput "$logRoot/map-hash.out.log" -RedirectStandardError "$logRoot/map-hash.err.log"
$handle = $process.Handle
if (-not $process.WaitForExit(120000)) { $process.Kill(); throw 'Map checksum timed out' }
$process.WaitForExit()
$output = [IO.File]::ReadAllText("$logRoot/map-hash.out.log") + [IO.File]::ReadAllText("$logRoot/map-hash.err.log")
Write-Output $output
if ($process.ExitCode -ne 0 -or $output -match '(SCRIPT ERROR:|ERROR:|WARNING:)' -or -not $output.Contains('PV_MAP_HASH_OK')) {
    throw 'Map checksum failed; inspect builds/validation/map-hash logs'
}
